add components, assets and slider
riri1199/need-for-drive pull request #1
Opened 2022-02-16 12:36 UTC by kotooo8080

Была добавлена верстка главной страницы сайта(V-01), добавлен переключаемый слайдер(F-01). 
Созданы следующие компоненты: InfoBlock - информационный блок сайта, LangSwitcher - переключаемая заглушка для смены языка, LocationChoice - выбор локации(заглушка на данный момент), MenuBlock - блок меню сайта, PageFooter и PageHeader - футер и хедер сайта, а также SliderBlock - переключаемый слайдер.
SVG социальных сетей вынесены в отдельный файл. Стили написаны с использованием SCSS.

2022-02-17 19:02 UTC, e3Y6 requested changes
Добавлены комментарии.

2022-02-17 19:02 UTC, e3Y6 commented on src/components/LangSwitcher.vue
> +            val: false,
Из названия не очень понятно, что означает переменная. Лучше назвать более понятней.

2022-02-17 19:02 UTC, e3Y6 commented on src/components/MenuBlock.vue
> +            toggle_value: false,
Лучше использовать один стиль именования переменных. В данном случае лучше написать в "camelCase".

2022-02-17 19:02 UTC, e3Y6 commented on src/components/MenuBlock.vue
> +        openOrClose() {
Может, лучше `openOrCloseLangSwitcher` или `toggleVisibilityLangSwitcher`?

2022-02-17 19:02 UTC, e3Y6 commented on src/components/SliderBlock.vue
> +            <button ref="more_details">Подробнее</button>
camelCase.

2022-02-17 19:02 UTC, e3Y6 commented on src/components/SliderBlock.vue
> +        buttonClick(leftOrRight) {
Может, лучше `flipSlide(isLeft)`?

2022-02-17 19:02 UTC, e3Y6 commented on src/components/SliderBlock.vue
> +    mounted() {
Лучше порядок опций устанавливать согласно документации (https://vuejs.org/style-guide/rules-recommended.html). Так порядок не будет разниться в компонентах.

2022-02-17 19:02 UTC, e3Y6 commented on src/components/MenuBlock.vue
> +                v-for="(item, indx) in items" :key=indx
Индекс в качестве ключа лучше не использовать. В данном случае можно добавить `id`.

2022-02-17 19:02 UTC, e3Y6 commented on src/pages/MainPage.vue
> +    components: {
Порядок опций лучше поменять.

2022-02-25 08:52 UTC, kotooo8080 commented on src/components/LangSwitcher.vue
> +            val: false,
Исправлено

2022-02-25 08:54 UTC, kotooo8080 commented on src/components/MenuBlock.vue
> +            toggle_value: false,
Исправлено

2022-02-25 08:55 UTC, kotooo8080 commented on src/components/MenuBlock.vue
> +        openOrClose() {
Исправлено

2022-02-25 08:57 UTC, kotooo8080 commented on src/components/SliderBlock.vue
> +            <button ref="more_details">Подробнее</button>
Исправлено

2022-02-25 09:00 UTC, kotooo8080 commented on src/components/SliderBlock.vue
> +        buttonClick(leftOrRight) {
Исправлено

2022-02-25 09:16 UTC, kotooo8080 commented on src/components/SliderBlock.vue
> +    mounted() {
Исправлено

2022-02-25 09:22 UTC, kotooo8080 commented on src/components/MenuBlock.vue
> +                v-for="(item, indx) in items" :key=indx
Исправлено

2022-02-25 09:23 UTC, kotooo8080 commented on src/pages/MainPage.vue
> +    components: {
Исправлено

2022-02-25 09:24 UTC, merged