add layout V-03 V-04 V-05
riri1199/need-for-drive pull request #3
Opened 2022-03-08 18:22 UTC by kotooo8080

Была добавлена верстка формы оформления заказа (шаг 2, 3, 4). Реализовано переключение вкладок(пока что не сохраняю данные заказа и не ограничила переход к незаполненным вкладкам - добавлю это в F-02), но реализовано добавление новых полей формы заказа и смена текста кнопки при переходе к соответствующим вкладкам. Исправлены некоторые моменты по верстке, в частности с высотой и прокруткой блока меню.

2022-03-11 15:24 UTC, e3Y6 requested changes

2022-03-11 15:24 UTC, e3Y6 commented on src/components/AdditionalBlock.vue
> +                    <img v-if="checkedServices.indexOf('ch1') + 1" src="../assets/img/checked.svg" alt="">
`checkedServices.indexOf('ch1') + 1` лучше вынести в `<script>`. Лучше сделать для всех выражений.

2022-03-11 15:24 UTC, e3Y6 commented on src/components/AdditionalBlock.vue
> +            startValue: '12.06.2019 12:00',
Лучше выбрать более понятное наименование. `value` не очень понятно.

2022-03-11 15:24 UTC, e3Y6 commented on src/components/AdditionalBlock.vue
> +            endValue: 'Введите дату и время',
Лучше выбрать более понятное наименование. `value` не очень понятно.

2022-03-11 15:24 UTC, e3Y6 commented on src/components/CarModel.vue
> +                v-for="(card, indx) in cards" :key="`card-item-${indx}`"
Для `key` лучше задать `id`.

2022-03-11 15:24 UTC, e3Y6 commented on src/components/CarModel.vue
> +
Пустую строку лучше убрать.

2022-03-11 15:24 UTC, e3Y6 commented on src/components/CarModel.vue
> +                :photo="card.photo"
Порядок атрибутов лучше установить согласно рекомендациям разработчиков Vue.

2022-03-11 15:24 UTC, e3Y6 commented on src/components/OrderCalc.vue
> +        <div class="order-model with-dots" v-if="pageIndx >= 1">
Порядок атрибутов лучше изменить.

2022-03-11 18:29 UTC, kotooo8080 commented on src/components/OrderCalc.vue
> +        <div class="order-model with-dots" v-if="pageIndx >= 1">
Исправлено

2022-03-11 19:31 UTC, kotooo8080 commented on src/components/CarModel.vue
> +                :photo="card.photo"
Исправлено

2022-03-11 19:31 UTC, kotooo8080 commented on src/components/CarModel.vue
> +
Исправлено

2022-03-11 19:45 UTC, riri1199 commented on src/components/AdditionalBlock.vue
> +            endValue: 'Введите дату и время',
Исправлено

2022-03-11 19:45 UTC, kotooo8080 commented on src/components/AdditionalBlock.vue
> +            startValue: '12.06.2019 12:00',
Исправлено

2022-03-11 20:45 UTC, kotooo8080 commented on src/components/AdditionalBlock.vue
> +                    <img v-if="checkedServices.indexOf('ch1') + 1" src="../assets/img/checked.svg" alt="">
Заменила выражение в условии на вызов функции и дополнительно заменила повторяющиеся блоки на циклы.

2022-03-11 20:50 UTC, kotooo8080 commented on src/components/CarModel.vue
> +                v-for="(card, indx) in cards" :key="`card-item-${indx}`"
Задала id

2022-03-14 07:53 UTC, e3Y6 approved these changes

2022-03-15 12:25 UTC, merged